# Generated by Django 4.0.4 on 2022-05-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sportitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportitem',
            name='isBorrowed',
            field=models.BooleanField(default=False),
        ),
    ]
