# Generated by Django 4.0.4 on 2022-04-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sportitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportitem',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
